### ISSUE TITLE
Integrate ESLint and set up code quality rules

### ISSUE THREAD

**Issue by Deadlyflamemaster** [priyaGangwar/Memory-Game#4]
Add Code Quality Metrics:
Task: Integrate code quality tools like ESLint (for JavaScript) or Pylint (for Python). Set up conventions for your project.
Issue: Integrate ESLint and set up code quality rules.
Issue: Configure CI pipeline to fail if code quality standards are not met.
Issue: Include metrics for code complexity, test coverage, and code duplication.

**Comment by priyaGangwar** [comment]
Done
